# Producer 3 Configuration

# Plugins
plugin = eosio::chain_api_plugin
plugin = eosio::producer_plugin
plugin = eosio::producer_api_plugin
plugin = eosio::net_plugin

# Producer settings
producer-name = producer3
signature-provider = EOS7qrnoGgXYMHYPmup2XHQNytpjHMgV5torsBmRNkXpdmPBZnGqL=KEY:5Jby8t9W6HFo7Nsc2m8T7McxDggnhqerWHFzH3d5y5bp4pqof2Z
enable-stale-production = true

# HTTP API
http-server-address = 0.0.0.0:8888
access-control-allow-origin = *
http-validate-host = false
verbose-http-errors = true

# P2P Network
p2p-listen-endpoint = 0.0.0.0:9876
p2p-peer-address = producer1:9876
p2p-peer-address = producer2:9876
p2p-peer-address = producer4:9876
p2p-peer-address = history:9876

# Performance
chain-state-db-size-mb = 4096
#reversible-blocks-db-size-mb = 1024
max-transaction-time = 500

# Logging
contracts-console = true

# BLS key for Savanna finality
signature-provider = PUB_BLS_eSJ31yOFEzDSPGqzJT-_ZmL0fLIhCc5PJaaSJm-wlHUlxhG-9GpsdzrvIr6PKxoOpbGzI9nzBxRRTF1T-UGAeB487dGUvoQlzdW333VPTKKoGUWCLgnLa6Y8V9ZchvoE3scL0A=KEY:PVT_BLS_pQwcf2phGvoQDz4RUcD84Lu8WCra-R5XEGiiXXisaXEidyJ2
